# Generated by Django 4.1.2 on 2023-01-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Vision", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MangaRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Vision.mangas"
                    ),
                ),
            ],
            options={
                "ordering": ["rating"],
            },
        ),
    ]
