# Generated by Django 4.1.6 on 2023-04-29 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Vision", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mangas",
            name="type_manga",
        ),
    ]
