# Generated by Django 4.1.6 on 2023-02-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vision', '0005_alter_store_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
